server:
  port: 8080

spring:
  config:
    import: classpath:database.yml, classpath:oauth2.yml, classpath:iamport.yml
  profiles:
    include:
      - database
      - ouath2
      - iamport

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug # 하이버네이트가 생성하는 SQL 이 다보인다.
#    org.hibernate.type: trace
