spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  config:
    import: classpath:database.yml, classpath:oauth2.yml, classpath:iamport.yml
  profiles:
    group:
      local:
        - local-server
        - local-db
        - common-db
        - ouath2
        - iamport
      prod:
        - heroku-server
        - heroku-db
        - common-db
        - oauth2
        - iamport

---
spring:
  config:
    activate:
      on-profile: heroku-server

server:
  port: $PORT

---
spring:
  config:
    activate:
      on-profile: local-server

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
