spring:
  profiles:
    include: jwt

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create # 자동으로 테이블 생성

    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true # db 커넥션을 트랜잭션에서만 하고 끝냄..


logging:
  level:
    org.hibernate.SQL: debug # 하이버네이트가 생성하는 SQL 이 다보인다.
#    org.hibernate.type: trace


iamport:
  restkey: 0349213312895772
  secret: 33cc95c0a912987164e4c8dbef320288f8da0843b93daf2cede64b6d237b9b28d0360c8b3d60108c