spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: cbc6e3857479a16b7062b156895a4048
            client-secret: cjCNpVn38CADgXxx7zppxHjkgPF8BYZs
            redirect-uri: http://localhost:3000/oauth/kakao/redirect
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - account_email

          naver:
            client-id: r1NwJ1du3WRNIHCP7psH
            client-secret: GedAo9py3u
            redirect-uri: http://localhost:3000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Naver
            scope:
              - name
              - profile_image

          google:
            client-id: 825611521308-0o9gpiccjospb4fk4m8j3m6smsmjmrst
            client-secret: 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
            redirect-uri: http://localhost:3000/login/oauth2/code/google
            scope:
              - profile
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect


